Hw2
Frontend-Sirius-VK/2022-autumn-d.kaymanov pull request #2
Opened 2022-12-02 23:25 UTC by kaimangeek

2022-12-06 18:18 UTC, StealthTech requested changes
Папка Photos не должна называться с большой буквы и лежать в папке components, т.к. картинка — не компонент. Если это картинки для базы, положи их в папку server/images, например

2022-12-06 18:18 UTC, StealthTech commented on components/Categories/Categories.css
> +    height: 44px;
Лучше стараться не делать размеры в не-круглых числах пикселей ни для чего кроме картинок (напр. 100px — ОК, 97px — НЕ ОК)

2022-12-06 18:18 UTC, StealthTech commented on components/Categories/Categories.css
> +    background-color: #DB3727;
Давай вынесем в палитру в CSS Custom Variables

2022-12-06 18:18 UTC, StealthTech commented on components/Categories/Categories.js
> +    render() {
Стоит переписать на handlebars

2022-12-06 18:18 UTC, StealthTech commented on components/ProductCard/ProductCard.css
> +.productCard {
Тут camelCase, ниже dash-case. Давай выберем один стиль? И лучше сделать по БЭМ: https://bem.info/

2022-12-06 18:18 UTC, StealthTech commented on components/ProductCardsRender/productCardsRender.js
> +            productCard.render(product.altimg, product.srcimg, product.namecar, product.spec, product.price, product.yearcar, product.mileage);
Можно в productCard.render() сделать внутри деструктуризацию и передавать сразу product

2022-12-06 18:18 UTC, StealthTech commented on controllers/MainController.js
> +import {ProductCarData} from "../models/productCarData.js";
Рекомендую использовать одинарные кавычки

2022-12-06 18:18 UTC, StealthTech commented on models/productCarData.js
> +            EventBus.emit('getCarSpec', data);
Лучше что-то вроде product-car-data:got-data или product-car-data:is-loaded

2022-12-06 18:18 UTC, StealthTech commented on server.js
> +const {getCarSpec} = require("./database/databasepg");
Либо одинарные, либо двойные кавычки юзаем. Лучше одинарные!

2022-12-06 18:18 UTC, StealthTech commented on database/databasepg.js
> +    password: 'qwerty',
В учебном проекте ОК, но в реальных проектах **никогда** не храним логины/пароли от сервисов в публичном гите

2022-12-06 18:18 UTC, StealthTech commented on server.js
>  const express = require('express');
server.js, database, картинки для данных — лучше вынести в отдельную папку

2022-12-07 14:12 UTC, Betchika99 reviewed
Давай еще нормально ПР назовем, как это было в ДЗ №1

2022-12-08 20:46 UTC, StealthTech requested changes

2022-12-08 20:46 UTC, StealthTech commented on components/Categories/Categories.css
> +    color: var(--text_header_color);
Принято называть переменные через dash-case

2022-12-08 20:46 UTC, StealthTech commented on components/Categories/Categories.css
> +    height: 44px;
Не учтено

2022-12-08 20:46 UTC, StealthTech commented on routing/Router.js
> +        console.log(result.controller)
Не должно быть console.log в коде на продакшене

2022-12-08 20:46 UTC, StealthTech commented on server/server.js
> +app.get('/login', (req,res) => {
login не нужен, авторизация больше не присутствует в требованиях

2022-12-08 20:46 UTC, StealthTech commented on views/CarView.js
> +        EventBus.on('getOneCarSpec', this.update.bind(this));
Не учтен коммент про тип события

2022-12-08 20:46 UTC, StealthTech commented on views/CarView.js
> +        // this.carSheet.render(carContainer);
Закомментированный код не должен попадать в сборку

2022-12-08 21:53 UTC, kaimangeek commented
![Снимок экрана от 2022-12-09 00-52-11](https://user-images.githubusercontent.com/57715631/206575322-9eaf42be-cb96-469e-8df7-facb96d48f80.png)

2022-12-08 21:55 UTC, StealthTech approved these changes

2022-12-08 21:56 UTC, merged