Домашнее задание №3
Frontend-Sirius-VK/2022-autumn-d.kaymanov pull request #3
Opened 2022-12-09 23:30 UTC by kaimangeek

2022-12-09 23:34 UTC, kaimangeek commented
![image](https://user-images.githubusercontent.com/57715631/206811767-34212f17-5db0-426f-8f61-04a898fc2338.png)
![image](https://user-images.githubusercontent.com/57715631/206811836-ecbf5bbe-315a-434b-a131-c41598296bc9.png)
![image](https://user-images.githubusercontent.com/57715631/206811886-e06f86af-c070-4cdd-84f3-ba2eeee64274.png)
![image](https://user-images.githubusercontent.com/57715631/206811911-ed300350-eb81-4dad-ac63-339967245924.png)
![image](https://user-images.githubusercontent.com/57715631/206812009-d7923d21-f6af-4673-942d-f6d760da8e61.png)
![image](https://user-images.githubusercontent.com/57715631/206812032-2e6391ea-e59c-43aa-8cfd-4444e8e500e1.png)
Скриншоты демонстрирующие все нововведения

2022-12-13 21:51 UTC, Betchika99 requested changes
ниже замечания по ДЗ3, которые уже оказались в мастере (поправь пожалуйста)

**server/server.js:**
- [x] урлы для сущностей называем по rest. и для роутинга на фронтенде, и для урлов на бекенде
- [x] [логи](https://github.com/Frontend-Sirius-VK/2022-autumn-d.kaymanov/blob/main/server/server.js#L31) убираем
- [x] на сервере нет обработки ошибок, т.е. статусы, которые ты проверяешь на фронте, никогда не будут проставлены (да-да, их надо ручками проставлять на сервере)
- [x] желательно, чтобы обработчик [app.listen](https://github.com/Frontend-Sirius-VK/2022-autumn-d.kaymanov/blob/main/server/server.js#L24) был в самом конце файла, чтобы его было просто найти и он не затерялся среди остальных обработчиков запросов
- [x] async/await обязательно оборачиваем в try/catch (иначе потеряем исключения!)
- [x] во всем проекте вижу путанницу с сущностями - есть [пост](https://github.com/Frontend-Sirius-VK/2022-autumn-d.kaymanov/blob/main/server/server.js#L34), есть [машина](https://github.com/Frontend-Sirius-VK/2022-autumn-d.kaymanov/blob/main/server/server.js#L40). давай использовать что-то одно
- [x] лишняя строка в коде https://github.com/Frontend-Sirius-VK/2022-autumn-d.kaymanov/blob/main/server/server.js#L20
- [ ] в обработчиках, в которых на фронте ожидается одна сущность (например, /getOneCarSpec/:id) надо добавить кода, чтобы возвращалась одна сущность, а не массив с этой одной сущностью
- [x] поломанный урл здесь https://github.com/Frontend-Sirius-VK/2022-autumn-d.kaymanov/blob/main/server/server.js#L19 (поэтому при обновлении страницы localhost:3000/car/1 всё ломается)
- [x] проверить корректность возвращаемых кодов ответа по ручкам создания/изменения/удаления сущности Объявление
- [x] ни в одном обработчике на сервере нет валидации данных (что данные действительно пришли с фронта корректные)
- [x] метод delete не должен [возвращать тело ](https://github.com/Frontend-Sirius-VK/2022-autumn-d.kaymanov/blob/main/server/server.js#L57)


**routing/Router.js**
- [x] [функция getID](https://github.com/Frontend-Sirius-VK/2022-autumn-d.kaymanov/blob/main/routing/Router.js#L36) не нужна. получится айди можно с помощью той же регулярки в функции invokeController
- [x] лучше использовать деструктуризацию [здесь](https://github.com/Frontend-Sirius-VK/2022-autumn-d.kaymanov/blob/main/routing/Router.js#L52): `const {pathname} = window.location;`
- [ ] не всем контроллерам нужен [id в process](https://github.com/Frontend-Sirius-VK/2022-autumn-d.kaymanov/blob/main/routing/Router.js#L68), нужно добавить какой-то флаг и проверку перед вызовом этого метода с параметром 
- [x] [эту логику](https://github.com/Frontend-Sirius-VK/2022-autumn-d.kaymanov/blob/main/routing/Router.js#L57-L60) можно заменить просто `return Boolean(matches)`
- [ ] упущена важная логика - при переходах между страницами (чем управляет лоадер), нужно отписываться от всех событий (кликов, eventbus-событий и т.п.). иначе при повторном переходе события будут дублироваться и будет какой-то хаус (потенциальная утечка памяти)


**про адаптив:**
- [x] при мобильном разрешении картинки на главной сплющиваются
<img width="557" alt="Снимок экрана 2022-12-14 в 00 24 16" src="https://user-images.githubusercontent.com/34346716/207447789-602774ca-5116-4d92-870f-ddbe357586c9.png">

- [x] при десктопном разрешении картинка на странице объявления тоже сплющивается
<img width="994" alt="Снимок экрана 2022-12-14 в 00 28 47" src="https://user-images.githubusercontent.com/34346716/207447709-ed08e3f9-633d-4fa7-ab0f-20f66102aca6.png">

- [ ] бургер с меню сейчас "тупой" - по нажатию на него ничего не происходит. либо убираем меню, либо доделываем логику до конца

- [x]  боковые отступы в шапке разные, что портит дизайн :(
![image](https://user-images.githubusercontent.com/34346716/207451372-85799519-e86e-4647-af96-4eefb338d07c.png)

**Дедлайн на исправление замечаний: четверг 23:59**

2022-12-13 21:51 UTC, Betchika99 commented on components/CarSheet/CarSheet.js
> +
лишние строки убираем

2022-12-13 21:51 UTC, Betchika99 commented on components/CarSheet/CarSheet.js
> +        const idCar = id;
переменная не используется

2022-12-13 21:51 UTC, Betchika99 commented on components/CarSheet/CarSheet.js
>          const {id, altimg, srcimg, namecar, spec, price, yearcar, mileage} = data[0];
почему здесь data - это массив? у тебя же только одна машинка на странице. нужно эту обработку сделать на сервере и на клиент вернуть удобные данные для работы

2022-12-13 21:51 UTC, Betchika99 commented on components/CarSheet/CarSheet.js
> +        const headerCar__carNameDiv = document.createElement('div');
такие страшные переменные лучше не делать. да, БЭМ хорош, но только в классах. переменные называем удобно и читаемо!)

2022-12-13 21:51 UTC, Betchika99 commented on components/ProductCardsRender/productCardsRender.js
> +            const loader = new Loader(this.container);
желательно здесь лоадер отцентровать по вертикали (например, только в этом случае навешивать контейнеру какой-то класс, который позволит лоадеру встать по центру)

![image](https://user-images.githubusercontent.com/34346716/207446156-cde95868-aaf4-4fad-99f5-7cd0b54f5839.png)

2022-12-13 21:51 UTC, Betchika99 commented on components/loader/loader.css
> +    border: 5px solid rgb(0, 0, 0);
для цветов используем css переменные

2022-12-13 21:51 UTC, Betchika99 commented on main.css
> +.error-container-error-text__p{
перед { нужнен пробел

2022-12-13 21:51 UTC, Betchika99 commented on models/carData.js
> +                }
этот код вряд ли когда-то выполнится, т.к. на сервере нет таких обработчиков. здесь и далее

2022-12-13 21:51 UTC, Betchika99 commented on models/productCarsData.js
> +                    EventBus.emit('product-car-data:server-error', ['Ошибка 500', 'Ошибка обращения к сервису. Попробуйте обновить страницу.']);
а зачем для ошибок разные события? ты же все равно передаешь текстом, в чем проблема + обрабатываешь события одинаково. можно и одним событием обойтись

2022-12-13 21:51 UTC, Betchika99 commented on views/CarView.js
> +    }
можно наверно без этого метода. просто использовать renderError, потому что ошибка по дефолту у тебя здесь никогда рисоваться не будет

2022-12-13 21:51 UTC, Betchika99 commented on models/productCarsData.js
> +                    EventBus.emit('product-car-data:server-error', ['Ошибка 500', 'Ошибка обращения к сервису. Попробуйте обновить страницу.']);
лучше возвращать не массив строк, а объект. типа {title: ... , description: ...}

2022-12-13 21:51 UTC, Betchika99 commented on views/MainView.js
> +        const root = document.querySelector('#root');
дубль кода с методом render. мб вынесем в конструктор и положим в поле класса?

2022-12-13 21:51 UTC, Betchika99 commented on views/MainView.js
> +    }
при такой реализации над ошибкой будет крутиться бесконечный лоадер. надо его убирать не только, когда данные пришли, но и когда ошибка произошла

![image](https://user-images.githubusercontent.com/34346716/207449446-4ffa81fe-8fd2-4673-b006-76c8b187c1ea.png)

2022-12-13 21:51 UTC, Betchika99 commented on views/MainView.js
> +        root.append(this.container);
ошибки тоже лучше центровать по вертикали (см. аналогичный коммент про лоадер)

2022-12-13 21:51 UTC, Betchika99 commented on components/Header/Header.js
> +        menu.textContent = '☰';
хитро) скорее всего не будет во всех браузерах работать из-за кодировки (на будущее лучше использовать иконку, сейчас можно не исправлять)

2022-12-13 21:51 UTC, Betchika99 commented on components/CarSheet/CarSheet.js
> +        owner__data.textContent = 'Дмитрий К.'
мы все данные берем из БД))) телефона и комментариев тоже касается

2022-12-13 21:51 UTC, Betchika99 commented on components/CarSheet/CarSheet.js
>          const {id, altimg, srcimg, namecar, spec, price, yearcar, mileage} = data[0];
ты используешь дальше все деструктуризированные данные, но не проверяешь, что они действительно есть. может быть вот такая ситуация:

![image](https://user-images.githubusercontent.com/34346716/207451131-0e82d7ca-0f53-4513-9d7f-ffb73f3b77a3.png)

2022-12-14 06:33 UTC, kaimangeek commented on components/CarSheet/CarSheet.js
> +
+

2022-12-14 06:35 UTC, kaimangeek commented on components/CarSheet/CarSheet.js
> +        const idCar = id;
Сделал

2022-12-14 06:39 UTC, kaimangeek commented on components/Header/Header.js
> +        menu.textContent = '☰';
Окей

2022-12-14 06:49 UTC, kaimangeek commented on components/ProductCardsRender/productCardsRender.js
> +            const loader = new Loader(this.container);
Сделал

2022-12-14 11:54 UTC, kaimangeek commented on main.css
> +.error-container-error-text__p{
Сделал

2022-12-14 20:31 UTC, kaimangeek commented on components/CarSheet/CarSheet.js
>          const {id, altimg, srcimg, namecar, spec, price, yearcar, mileage} = data[0];
Сделал

2022-12-14 20:33 UTC, kaimangeek commented on components/CarSheet/CarSheet.js
> +        const headerCar__carNameDiv = document.createElement('div');
Больше так не буду, но зря старался что-ли

2022-12-14 20:33 UTC, kaimangeek commented on components/loader/loader.css
> +    border: 5px solid rgb(0, 0, 0);
Сделал

2022-12-14 20:34 UTC, kaimangeek commented on models/carData.js
> +                }
Добавил обработчики

2022-12-14 20:36 UTC, kaimangeek commented on models/productCarsData.js
> +                    EventBus.emit('product-car-data:server-error', ['Ошибка 500', 'Ошибка обращения к сервису. Попробуйте обновить страницу.']);
Так вывод то разный, можно конечно сделать элегантнее, но я просто по примеру сделал(

2022-12-14 20:38 UTC, kaimangeek commented on views/CarView.js
> +    }
Без функции не работает

2022-12-14 20:39 UTC, kaimangeek commented on views/MainView.js
> +    }
Сделал

2022-12-14 20:39 UTC, kaimangeek commented on views/MainView.js
> +        root.append(this.container);
Сделал

2022-12-14 20:40 UTC, kaimangeek commented on components/CarSheet/CarSheet.js
>          const {id, altimg, srcimg, namecar, spec, price, yearcar, mileage} = data[0];
Я проверяю пришла ли наша дата, а если с ней что-то не так то страница не отрисуется

2022-12-14 20:46 UTC, kaimangeek commented on models/productCarsData.js
> +                    EventBus.emit('product-car-data:server-error', ['Ошибка 500', 'Ошибка обращения к сервису. Попробуйте обновить страницу.']);
Сделал

2022-12-14 20:50 UTC, kaimangeek commented on views/MainView.js
> +        const root = document.querySelector('#root');
Сделал

2022-12-14 21:00 UTC, kaimangeek commented on components/CarSheet/CarSheet.js
> +        owner__data.textContent = 'Дмитрий К.'
Сделал

2022-12-14 22:00 UTC, Betchika99 commented on components/CarSheet/CarSheet.js
> +        const headerCar__carNameDiv = document.createElement('div');
ну вот откроет твой будущий работодатель этот код и что он скажет :(

2022-12-14 22:00 UTC, Betchika99 commented on views/CarView.js
> +    }
слабый аргумент. в чем проблема?

2022-12-15 06:08 UTC, kaimangeek commented on components/CarSheet/CarSheet.js
> +        const headerCar__carNameDiv = document.createElement('div');
Я когда на хэндлбарс переписывать буду этот код всё равно исчезнет, а переписывать буду как только пуллреквест исчезнет

2022-12-15 06:20 UTC, kaimangeek commented on views/CarView.js
> +    }
Избавился от этой функции

2022-12-16 15:06 UTC, Betchika99 approved these changes
закрываем ДЗ с учетом фикса ошибок в ДЗ4 https://github.com/Frontend-Sirius-VK/2022-autumn-d.kaymanov/pull/4#issuecomment-1355026598

2022-12-16 15:07 UTC, merged