Домашнее задание №4
Frontend-Sirius-VK/2022-autumn-d.kaymanov pull request #4
Opened 2022-12-16 11:26 UTC by kaimangeek

2022-12-16 15:06 UTC, Betchika99 commented
должки из ДЗ3:

- [ ] убрать переменные в JS в формате БЭМ (в хенделбарс не будут меняться классы, поэтому аргумент не принят, но ок)
- [ ] не вижу обработки ошибок 404 и 400 на сервере, только 500тки
- [ ] урлы на сервере остались не по ресту
- [ ] метод delete не работает в случае успеха (соединение не закрывается)
- [ ] сломан роутинг по стрелкам в браузере (попробуй походить между твоими страницами туда/сюда, страница не обновляется)
- [ ] поправить hover состояние строк (чтобы оно не дергалось так эпилептично)
- [ ] вот такая реализация на троечку
```
if (result.controller !== controllerСheck) {
    controller.process(id);
}
```

потому что если у тебя будет еще один контроллер без айдишника (например, /login), то здесь проверка сломается. Поэтому лучше сделать что-то вроде white list с урлами, для которых нужны айдишки

2022-12-20 12:40 UTC, kaimangeek commented
```

2022-12-20 12:40 UTC, kaimangeek commented
```
server {
        server_name carshit.shop;

        root /home/ubuntu/workenv/2022-autumn-d.kaymanov/dist/;

        location / {
                try_files $uri $uri/ /index.html;
        }

        location /api/ {
                proxy_pass http://127.0.0.1:3000/api/;
        }
}
```

2022-12-20 12:41 UTC, kaimangeek commented
http://carshit.shop/

2022-12-20 22:48 UTC, StealthTech requested changes

2022-12-20 22:48 UTC, StealthTech commented on components/CarSheet/carsheet.handlebars
> +        <div class="carSheetContainer__headerCar__carNameDiv">
По БЭМ элемент бывает только у блока. Нельзя делать элемент от элемента

2022-12-20 22:48 UTC, StealthTech commented on dist/index.html
> +<!DOCTYPE html>
dist должен быть исключен из git

2022-12-20 22:48 UTC, StealthTech commented on package.json
> +    "cors": "^2.8.5",
Не нужно

2022-12-20 22:48 UTC, StealthTech commented on routing/Router.js
> +const controllerСheck = [new MainController()];
Массив из одного контроллера? На строке 77 сравниваем массив и контроллер?

2022-12-20 22:48 UTC, StealthTech commented on server/index.html
> +    <script src="index.js" type="module"></script>
Собираешь через webpack ведь

2022-12-20 22:48 UTC, StealthTech commented on server/index.js
> +window.addEventListener('popstate', (event) => {
Это можно сделать в start. А в stop сделать removeEventListener

2022-12-20 23:00 UTC, StealthTech submitted a review, later dismissed

2022-12-21 08:25 UTC, StealthTech approved these changes

2022-12-21 08:25 UTC, merged